name: CI

on:
  push:
    branches:
      - main
      - release-*
    tags: '*'
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
        os:
          - ubuntu-latest
        arch:
          - x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - uses: julia-actions/julia-buildpkg@v1
      - run: |
          # Install 32-bit headers
          sudo apt-get install libc6-dev-i386
          git clone https://github.com/iris-edu/libmseed
          # Patch library to prevent use of uninitialised file position
          sed -i 's|int64_t fpos;|int64_t fpos = 0;|g' libmseed/fileutils.c
          grep 'int64_t fpos = 0;' libmseed/fileutils.c
          make -C libmseed shared CC="gcc -m32"
          make -C libmseed install PREFIX=$PWD/libmseed
          # Override library provided by libmseed_jll
          echo '82273a5ca1f5bcc7ed5aa60d75b8536e360c9c41 = "/home/runner/work/LibMseed.jl/LibMseed.jl/libmseed"' > ~/.julia/artifacts/Overrides.toml
          # Confirm we're using the right one
          julia --project -E 'using libmseed_jll; libmseed'
      - uses: julia-actions/julia-runtest@v1
      - name: tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
